version: '3.8'

services:
  app:
    build: .
    ports:
      - '3000:3000'
    environment:
      - NODE_ENV=development
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: npm run dev

  test:
    build: .
    environment:
      - NODE_ENV=test
    volumes:
      - ./src:/usr/src/app/src
      - ./test:/usr/src/app/test
    command: npm run test
      