apiVersion: apps/v1
kind: Deployment
metadata:
  name: nexusflow-cicd-orchestrator
spec:
  replicas: 3
  selector:
    matchLabels:
      app: nexusflow-cicd-orchestrator
  template:
    metadata:
      labels:
        app: nexusflow-cicd-orchestrator
    spec:
      containers:
        - name: nexusflow-cicd-orchestrator
          image: marveloper/nexusflow-cicd-orchestrator:latest
          ports:
            - containerPort: 3000
          resources:
            limits:
              memory: "128Mi"
              cpu: "500m"
            requests:
              memory: "64Mi"
              cpu: "250m"
          readinessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          livenessProbe:
            httpGet:
              path: /api/health
              port: 3000
            initialDelaySeconds: 5
            periodSeconds: 5
          env:
            - name: NODE_ENV
              value: "production"